export default [
  {
    _id: 'eLiFaqxhpCsysHE4Y',
    pageId: '8frKkf95MG53g8H4P',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    demo: true,
    plainText: 'Your body has no limits. Run faster, try better and stay stronger.\n// \nInsert an image in the post to make it more visible for your audience. Remember, images and photos perform better on your social media pages',
    creatorId: 'uBD4LLggwF9Sf8p7f',
    createdAt: '2017-10-02T11:39:37.457Z',
    scheduledAt: '2017-10-04T11:39:37.457Z',
    images: [
      {
        uuid: 'R6YGx7gG8eiQzoaLWzj6',
        name: 'yadcgbslhce - william - stitt.jpg',
        url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/yadcgbslhce-william-stitt.jpg',
        width: 5184,
        height: 3456,
        type: 'image/jpeg',
      },
    ],
    mediaType: 'single-image',
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-03T10:39:37.457Z',
  },
  {
    _id: 'RxkDMNc3wshghEjrz',
    pageId: '8frKkf95MG53g8H4P',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    demo: true,
    plainText: "For what it's worth, it's never to late to be whoever you want to be.\n//\nAdd a simple text and engage with your audience. Ask them something, send a message, or just tell them about your last updates!",
    creatorId: 'uBD4LLggwF9Sf8p7f',
    createdAt: '2017-10-01T11:39:37.457Z',
    scheduledAt: '2017-10-03T21:39:37.457Z',
    approved: false,
    status: 'default',
    mediaType: 'no-media',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-03T07:39:37.457Z',
  },
  {
    _id: 'ncTvuzXPgFShyEP6d',
    pageId: '8frKkf95MG53g8H4P',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    creatorId: 'uBD4LLggwF9Sf8p7f',
    demo: true,
    createdAt: '2017-10-01T11:39:37.457Z',
    scheduledAt: '2017-10-07T11:39:37.457Z',
    link: {
      id: '716567301751292',
      description: 'Subscribe: http://www.youtube.com/user/TheMiro0r?sub_confirmation=1 Website: http://www.mateuszm.com Facebook: http://on.fb.me/R8jxxV Instagram: http://bit.l...',
      title: 'Unbroken',
      type: 'video.other',
      url: 'https://www.youtube.com/watch?v=26U_seo0a1g',
      image: {
        url: 'https://i.ytimg.com/vi/26U_seo0a1g/maxresdefault.jpg',
      },
    },
    mediaType: 'url-thumbnail',
    approved: true,
    status: 'default',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-02T11:39:37.457Z',
    plainText: "The future isn't tomorrow. It's today. Watch the full film and explore yourself.\n//\nAdd a Youtube video link, to share your last media work.",
  },
  {
    _id: 'JcMfyx2nFWuJdsTjG',
    pageId: '8frKkf95MG53g8H4P',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    demo: true,
    creatorId: 'uBD4LLggwF9Sf8p7f',
    createdAt: '2017-10-03T01:39:37.457Z',
    scheduledAt: '2017-10-03T15:39:37.457Z',
    link: {
      id: '1044118598975200',
      description: 'Find yourself losing interest in exercising and eating a healthy diet? Maybe you were gung ho for a few weeks and then your get-in-shape determination quickly faded -- and you went back to your old, bad health habits.',
      title: '10 Tips to Keep You Healthy',
      type: 'article',
      updated_time: '2017-09-23T11:39:37.457Z',
      url: 'http://www.webmd.com/diet/obesity/features/10-motivational-tips-to-keep-you-healthy',
      image: {
        url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/url-image.jpg',
      },
    },
    mediaType: 'url-thumbnail',
    approved: true,
    status: 'approved',
    published: false,
    scheduledSet: true,
    editedAt: '2017-10-03T01:39:37.457Z',
    plainText: "Consider the following tips to take on another level of your healthy lifestyle. Start with simple changes and you'll keep doing better.\n// \nHave an article to share? No problems, just paste the link into the past, and create the post.",
  },
  {
    _id: 'yy4fsreTjwazQQc6J',
    pageId: '8frKkf95MG53g8H4P',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    demo: true,
    creatorId: 'uBD4LLggwF9Sf8p7f',
    createdAt: '2017-09-28T11:39:37.457Z',
    scheduledAt: '2017-10-06T11:39:37.457Z',
    video: {
      type: 'video/mp4',
      uuid: 'Wg89FXKq5kZiGzNRSsBR',
      size: '14516774',
      url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/demo-video.mp4',
    },
    mediaType: 'video',
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: true,
    editedAt: '2017-10-03T11:34:37.457Z',
    plainText: 'This is the story you create. There is something more you can try today.\n// \nNo worries for native video on social media. Add a video as you would do on Facebook.',
  },
  {
    _id: 'XKdAMftfJLo3h2mXD',
    pageId: '8frKkf95MG53g8H4P',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    demo: true,
    creatorId: 'uBD4LLggwF9Sf8p7f',
    createdAt: '2017-10-02T20:39:37.457Z',
    scheduledAt: '2017-10-06T11:39:37.457Z',
    gif: {
      width: 1440,
      height: 1440,
      source: 'local',
      uuid: 'h99cmpCnZmtue339HSHp',
      size: 11092288,
      url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/gif-demo.gif',
    },
    mediaType: 'gif-image',
    approved: true,
    status: 'default',
    published: false,
    scheduledSet: true,
    editedAt: '2017-10-02T20:39:37.457Z',
    plainText: 'Be a hero! \n// \nShare a GIF with all the people you like!',
  },
  {
    _id: 'FDqrBr9Lt5Njaqpdj',
    pageId: 'Hm4Qyx4cAHQ8C395v',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    demo: true,
    plainText: "Champions aren't born. They are created.",
    creatorId: 'uBD4LLggwF9Sf8p7f',
    createdAt: '2017-10-02T11:39:37.515Z',
    scheduledAt: '2017-10-04T11:39:37.515Z',
    mediaType: 'single-image',
    images: [
      {
        uuid: 'R6YGx7gG8eiQzoaLWzj6',
        name: 'yadcgbslhce - william - stitt.jpg',
        url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/yadcgbslhce-william-stitt.jpg',
        width: 5184,
        height: 3456,
        type: 'image/jpeg',
      },
    ],
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-03T10:39:37.515Z',
  },
  {
    _id: 'gMzWd7JqEDvP492YX',
    pageId: 'Hm4Qyx4cAHQ8C395v',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    demo: true,
    plainText: "For what it's worth, it's never to late to be whoever you want to be.\n//\nAdd a simple text and engage with your audience. Ask them something, send a message, or just tell them about your last updates!",
    creatorId: 'uBD4LLggwF9Sf8p7f',
    mediaType: 'no-media',
    createdAt: '2017-10-01T11:39:37.515Z',
    scheduledAt: '2017-10-03T21:39:37.515Z',
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-03T07:39:37.515Z',
  },
  {
    _id: 'B3Dp44zma9iD6smfF',
    pageId: 'Hm4Qyx4cAHQ8C395v',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    demo: true,
    creatorId: 'uBD4LLggwF9Sf8p7f',
    createdAt: '2017-09-28T11:39:37.515Z',
    scheduledAt: '2017-10-08T11:39:37.515Z',
    mediaType: 'video',
    video: {
      type: 'video/mp4',
      uuid: 'Wg89FXKq5kZiGzNRSsBR',
      size: '14516774',
      url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/demo-video.mp4',
    },
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-03T11:34:37.515Z',
    plainText: 'This is the story you create. There is something more you can try today.\n// \nNo worries for native video on social media. Add a video as you would do on Facebook.',
  },
  {
    _id: 'id7tWcQfZjMor9dzs',
    pageId: 'Hm4Qyx4cAHQ8C395v',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    demo: true,
    creatorId: 'uBD4LLggwF9Sf8p7f',
    createdAt: '2017-10-02T20:39:37.515Z',
    scheduledAt: '2017-10-04T12:39:37.515Z',
    mediaType: 'gif-image',
    gif: {
      width: 1440,
      height: 1440,
      uuid: 'h99cmpCnZmtue339HSHp',
      source: 'local',
      size: 11092288,
      url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/gif-demo.gif',
    },
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-02T20:39:37.515Z',
    plainText: 'Be a hero! \n// \nShare a GIF with all the people you like!',
  },
  {
    _id: 'dQ5YwHwpk4dXmZRJ7',
    pageId: 'ueSiT8GN5PekDFdni',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    plainText: "Champions aren't born. They are created.",
    creatorId: 'uBD4LLggwF9Sf8p7f',
    demo: true,
    createdAt: '2017-10-02T11:39:37.538Z',
    scheduledAt: '2017-10-04T11:39:37.538Z',
    images: [
      {
        uuid: 'R6YGx7gG8eiQzoaLWzj6',
        name: 'yadcgbslhce - william - stitt.jpg',
        url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/image-insta.jpg',
        width: 5184,
        height: 3456,
        type: 'image/jpeg',
      },
    ],
    mediaType: 'single-image',
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-03T10:39:37.538Z',
  },
  {
    _id: 'DruKh97Wcttg5MWMv',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    pageId: 'uFxSNHJ5yY6Zb2aXN',
    images: [
      {
        uuid: 'KsKwAZQcLZbW3fg8M',
        width: 1360,
        height: 746,
        type: 'image/png',
        size: 55680,
        name: '04.0.1.png',
        url: 'https://d29fp8qybdwwik.cloudfront.net/uBD4LLggwF9Sf8p7f/6qE7W6xxZH-04-0-1.png',
      },
    ],
    mediaType: 'single-image',
    createdAt: '2017-10-03T11:42:09.759Z',
    creatorId: 'uBD4LLggwF9Sf8p7f',
    approved: true,
    status: 'published',
    published: true,
    scheduledSet: false,
    publishedPostId: '6320945861190918144',
  },
  {
    _id: 'fzgXwEsDYfQZbTjDB',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    pageId: '8frKkf95MG53g8H4P',
    images: [
      {
        uuid: 'CHxLJ9eLLBEhqhoYi',
        width: 1360,
        height: 746,
        type: 'image/png',
        size: 80904,
        name: '03.0.3.png',
        url: 'https://d29fp8qybdwwik.cloudfront.net/uBD4LLggwF9Sf8p7f/PB37mBgJBb-03-0-3.png',
      },
      {
        uuid: 'd6g2Yy3rx4f4iZhFH',
        width: 1360,
        height: 746,
        type: 'image/png',
        size: 55680,
        name: '04.0.1.png',
        url: 'https://d29fp8qybdwwik.cloudfront.net/uBD4LLggwF9Sf8p7f/mhJWGWEsCu-04-0-1.png',
      },
      {
        uuid: 'fpCNWEdx9b5aERses',
        width: 1360,
        height: 746,
        type: 'image/png',
        size: 80904,
        name: '97b5c599-3d31-4976-b759-ca12bac7cd00.png',
        url: 'https://d29fp8qybdwwik.cloudfront.net/uBD4LLggwF9Sf8p7f/eCEbBdtXBG-97b5c599-3d31-4976-b759-ca12bac7cd00.png',
      },
    ],
    mediaType: 'multiple-images',
    createdAt: '2017-10-03T12:07:39.402Z',
    creatorId: 'uBD4LLggwF9Sf8p7f',
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: false,
  },
  {
    _id: 'odWCyhhJjqb4Zc4oa',
    workspaceId: '9u8MNKJvTCb9nCrFp',
    pageId: 'HESZP675yt38twHaL',
    plainText: 'techcrunch.com/2010/10/30/top-30-android-apps/',
    content: {
      entityMap: {},
      blocks: [
        {
          key: 'e9ev4',
          text: 'techcrunch.com/2010/10/30/top-30-android-apps/',
          type: 'unstyled',
          depth: 0,
          inlineStyleRanges: [],
          entityRanges: [],
          data: {},
        },
      ],
    },
    mediaType: 'url-carousel',
    urlCarousel: {
      links: [
        {
          title: 'Top 30 Android Apps Of All Time',
          description: "With the ubiquitous media coverage surrounding the iOS (iPhone, iPad, iPod Touch) app market, it's important to remember that Android also is making huge..",
          type: 'article',
          url: 'http://techcrunch.com/2010/10/30/top-30-android-apps/',
          image: {
            url: 'https://d29fp8qybdwwik.cloudfront.net/uBD4LLggwF9Sf8p7f/He8rGmbxow-images-1.jpg',
            uuid: '42jpGHuRfikCi7yrz',
          },
        },
        {
          title: 'Top 30 Android Apps Of All Time',
          description: "With the ubiquitous media coverage surrounding the iOS (iPhone, iPad, iPod Touch) app market, it's important to remember that Android also is making huge..",
          type: 'article',
          url: 'http://techcrunch.com/2010/10/30/top-30-android-apps/',
          image: {
            url: 'https://d29fp8qybdwwik.cloudfront.net/uBD4LLggwF9Sf8p7f/ista3aQfus-misc285.jpg',
            uuid: 'MCMyEv54rQpidyvzw',
          },
        },
      ],
      multi_share_end_card: true,
    },
    createdAt: '2017-10-03T16:39:45.108Z',
    fbPageTags: [],
    creatorId: 'uBD4LLggwF9Sf8p7f',
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: false,
  },
  {
    _id: 'tHASzvCZLCTbWwJSQ',
    pageId: 'Tb3n3CYTxQiRWogH6',
    workspaceId: '5fuecEAofRxiS6nJK',
    demo: true,
    plainText: 'Your body has no limits. Run faster, try better and stay stronger.\n// \nInsert an image in the post to make it more visible for your audience. Remember, images and photos perform better on your social media pages',
    creatorId: 'X7AX3yHDigLJe6TWt',
    createdAt: '2017-10-03T12:40:19.575Z',
    scheduledAt: '2017-10-05T12:40:19.575Z',
    images: [
      {
        uuid: 'R6YGx7gG8eiQzoaLWzj6',
        name: 'yadcgbslhce - william - stitt.jpg',
        url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/yadcgbslhce-william-stitt.jpg',
        width: 5184,
        height: 3456,
        type: 'image/jpeg',
      },
    ],
    mediaType: 'single-image',
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-04T11:40:19.575Z',
  },
  {
    _id: 'fukQG5kBA8K7GGYBT',
    pageId: 'Tb3n3CYTxQiRWogH6',
    workspaceId: '5fuecEAofRxiS6nJK',
    demo: true,
    plainText: "For what it's worth, it's never to late to be whoever you want to be.\n//\nAdd a simple text and engage with your audience. Ask them something, send a message, or just tell them about your last updates!",
    creatorId: 'X7AX3yHDigLJe6TWt',
    createdAt: '2017-10-02T12:40:19.575Z',
    scheduledAt: '2017-10-04T22:40:19.575Z',
    approved: false,
    status: 'default',
    mediaType: 'no-media',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-04T08:40:19.575Z',
  },
  {
    _id: 'iuLM4erbuX5Tspqv3',
    pageId: 'Tb3n3CYTxQiRWogH6',
    workspaceId: '5fuecEAofRxiS6nJK',
    creatorId: 'X7AX3yHDigLJe6TWt',
    demo: true,
    createdAt: '2017-10-02T12:40:19.575Z',
    scheduledAt: '2017-10-08T12:40:19.575Z',
    link: {
      id: '716567301751292',
      description: 'Subscribe: http://www.youtube.com/user/TheMiro0r?sub_confirmation=1 Website: http://www.mateuszm.com Facebook: http://on.fb.me/R8jxxV Instagram: http://bit.l...',
      title: 'Unbroken',
      type: 'video.other',
      url: 'https://www.youtube.com/watch?v=26U_seo0a1g',
      image: {
        url: 'https://i.ytimg.com/vi/26U_seo0a1g/maxresdefault.jpg',
      },
    },
    mediaType: 'url-thumbnail',
    approved: true,
    status: 'default',
    published: false,
    scheduledSet: false,
    editedAt: '2017-10-03T12:40:19.575Z',
    plainText: "The future isn't tomorrow. It's today. Watch the full film and explore yourself.\n//\nAdd a Youtube video link, to share your last media work.",
  },
  {
    _id: 'Ex2wNNtPPcBGMy6yG',
    pageId: 'Tb3n3CYTxQiRWogH6',
    workspaceId: '5fuecEAofRxiS6nJK',
    demo: true,
    creatorId: 'X7AX3yHDigLJe6TWt',
    createdAt: '2017-10-04T02:40:19.575Z',
    scheduledAt: '2017-10-04T16:40:19.575Z',
    link: {
      id: '1044118598975200',
      description: 'Find yourself losing interest in exercising and eating a healthy diet? Maybe you were gung ho for a few weeks and then your get-in-shape determination quickly faded -- and you went back to your old, bad health habits.',
      title: '10 Tips to Keep You Healthy',
      type: 'article',
      updated_time: '2017-09-24T12:40:19.575Z',
      url: 'http://www.webmd.com/diet/obesity/features/10-motivational-tips-to-keep-you-healthy',
      image: {
        url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/url-image.jpg',
      },
    },
    mediaType: 'url-thumbnail',
    approved: true,
    status: 'approved',
    published: false,
    scheduledSet: true,
    editedAt: '2017-10-04T02:40:19.575Z',
    plainText: "Consider the following tips to take on another level of your healthy lifestyle. Start with simple changes and you'll keep doing better.\n// \nHave an article to share? No problems, just paste the link into the past, and create the post.",
  },
  {
    _id: 'asxQgGD5pb236Sica',
    pageId: 'Tb3n3CYTxQiRWogH6',
    workspaceId: '5fuecEAofRxiS6nJK',
    demo: true,
    creatorId: 'X7AX3yHDigLJe6TWt',
    createdAt: '2017-09-29T12:40:19.575Z',
    scheduledAt: '2017-10-07T12:40:19.575Z',
    video: {
      type: 'video/mp4',
      uuid: 'Wg89FXKq5kZiGzNRSsBR',
      size: '14516774',
      url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/demo-video.mp4',
    },
    mediaType: 'video',
    approved: false,
    status: 'default',
    published: false,
    scheduledSet: true,
    editedAt: '2017-10-04T12:35:19.575Z',
    plainText: 'This is the story you create. There is something more you can try today.\n// \nNo worries for native video on social media. Add a video as you would do on Facebook.',
  },
  {
    _id: '7E48s9dpZh2r9ET9b',
    pageId: 'Tb3n3CYTxQiRWogH6',
    workspaceId: '5fuecEAofRxiS6nJK',
    demo: true,
    creatorId: 'X7AX3yHDigLJe6TWt',
    createdAt: '2017-10-03T21:40:19.575Z',
    scheduledAt: '2017-10-07T12:40:19.575Z',
    gif: {
      width: 1440,
      height: 1440,
      source: 'local',
      uuid: 'h99cmpCnZmtue339HSHp',
      size: 11092288,
      url: 'https://d2b57pa8jvjkcd.cloudfront.net/static/demo/gif-demo.gif',
    },
    mediaType: 'gif-image',
    approved: true,
    status: 'default',
    published: false,
    scheduledSet: true,
    editedAt: '2017-10-03T21:40:19.575Z',
    plainText: 'Be a hero! \n// \nShare a GIF with all the people you like!',
  },
];
